/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiesgoRouteImport } from './routes/riesgo'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders.index'
import { Route as PurchaseOrdersIdRouteImport } from './routes/purchase-orders.$id'
import { Route as MaquinaIdRouteImport } from './routes/maquina.$id'

const RiesgoRoute = RiesgoRouteImport.update({
  id: '/riesgo',
  path: '/riesgo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchaseOrdersRoute,
} as any)
const PurchaseOrdersIdRoute = PurchaseOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchaseOrdersRoute,
} as any)
const MaquinaIdRoute = MaquinaIdRouteImport.update({
  id: '/maquina/$id',
  path: '/maquina/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof ConfiguracionRoute
  '/engineering': typeof EngineeringRoute
  '/intake': typeof IntakeRoute
  '/production': typeof ProductionRoute
  '/purchase-orders': typeof PurchaseOrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/riesgo': typeof RiesgoRoute
  '/maquina/$id': typeof MaquinaIdRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof ConfiguracionRoute
  '/engineering': typeof EngineeringRoute
  '/intake': typeof IntakeRoute
  '/production': typeof ProductionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/riesgo': typeof RiesgoRoute
  '/maquina/$id': typeof MaquinaIdRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof ConfiguracionRoute
  '/engineering': typeof EngineeringRoute
  '/intake': typeof IntakeRoute
  '/production': typeof ProductionRoute
  '/purchase-orders': typeof PurchaseOrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/riesgo': typeof RiesgoRoute
  '/maquina/$id': typeof MaquinaIdRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/engineering'
    | '/intake'
    | '/production'
    | '/purchase-orders'
    | '/reset-password'
    | '/riesgo'
    | '/maquina/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/engineering'
    | '/intake'
    | '/production'
    | '/reset-password'
    | '/riesgo'
    | '/maquina/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracion'
    | '/engineering'
    | '/intake'
    | '/production'
    | '/purchase-orders'
    | '/reset-password'
    | '/riesgo'
    | '/maquina/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EngineeringRoute: typeof EngineeringRoute
  IntakeRoute: typeof IntakeRoute
  ProductionRoute: typeof ProductionRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiesgoRoute: typeof RiesgoRoute
  MaquinaIdRoute: typeof MaquinaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riesgo': {
      id: '/riesgo'
      path: '/riesgo'
      fullPath: '/riesgo'
      preLoaderRoute: typeof RiesgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof PurchaseOrdersRoute
    }
    '/purchase-orders/$id': {
      id: '/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof PurchaseOrdersIdRouteImport
      parentRoute: typeof PurchaseOrdersRoute
    }
    '/maquina/$id': {
      id: '/maquina/$id'
      path: '/maquina/$id'
      fullPath: '/maquina/$id'
      preLoaderRoute: typeof MaquinaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PurchaseOrdersRouteChildren {
  PurchaseOrdersIdRoute: typeof PurchaseOrdersIdRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
}

const PurchaseOrdersRouteChildren: PurchaseOrdersRouteChildren = {
  PurchaseOrdersIdRoute: PurchaseOrdersIdRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
}

const PurchaseOrdersRouteWithChildren = PurchaseOrdersRoute._addFileChildren(
  PurchaseOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EngineeringRoute: EngineeringRoute,
  IntakeRoute: IntakeRoute,
  ProductionRoute: ProductionRoute,
  PurchaseOrdersRoute: PurchaseOrdersRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RiesgoRoute: RiesgoRoute,
  MaquinaIdRoute: MaquinaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
