/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiesgoRouteImport } from './routes/riesgo'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaquinaIdRouteImport } from './routes/maquina.$id'

const RiesgoRoute = RiesgoRouteImport.update({
  id: '/riesgo',
  path: '/riesgo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinaIdRoute = MaquinaIdRouteImport.update({
  id: '/maquina/$id',
  path: '/maquina/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/riesgo': typeof RiesgoRoute
  '/maquina/$id': typeof MaquinaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/riesgo': typeof RiesgoRoute
  '/maquina/$id': typeof MaquinaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/riesgo': typeof RiesgoRoute
  '/maquina/$id': typeof MaquinaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracion' | '/riesgo' | '/maquina/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracion' | '/riesgo' | '/maquina/$id'
  id: '__root__' | '/' | '/configuracion' | '/riesgo' | '/maquina/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  RiesgoRoute: typeof RiesgoRoute
  MaquinaIdRoute: typeof MaquinaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riesgo': {
      id: '/riesgo'
      path: '/riesgo'
      fullPath: '/riesgo'
      preLoaderRoute: typeof RiesgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquina/$id': {
      id: '/maquina/$id'
      path: '/maquina/$id'
      fullPath: '/maquina/$id'
      preLoaderRoute: typeof MaquinaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  RiesgoRoute: RiesgoRoute,
  MaquinaIdRoute: MaquinaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
